name: Build and deploy Azure Function App

on:
  workflow_dispatch: {}
  push:

env:
  AZURE_FUNCTIONAPP_NAME: ${{ vars.AZURE_FUNCTIONAPP_NAME }}
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Bz.Fott.Telemetry.LapTimeProcessorAzFunctions'
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCAPP_PUBLISH_PROFILE }}
  DOTNET_VERSION: '6.0'
  CONFIGURATION: Release
  WORKING_DIRECTORY: .

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2
    
    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}/src/Bz.Fott.Telemetry.LapTimeProcessorAzFunctions/"

    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}/src/Bz.Fott.Telemetry.LapTimeProcessorAzFunctions/" --configuration ${{ env.CONFIGURATION }} --no-restore --output '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}